spring:
  #  mvc:
  #    contentnegotiation:
  #      favor-parameter: true
  #      media-types:
  #      #pdf: application/pdf
  #        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:sqlserver://idelity-test.database.windows.net:1433;database=registraduria-app;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    #driverClassName: org.h2.Driver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #platform: h2
    username: idelity-test@idelity-test
    #username: sa
    password: Dontknow1
    #password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true